config/routes.rb
Rails.application.routes.draw do
  resources :year_ending_odometers

  resources :filings

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # Routes for Static Pages

  get "/mainmenu", :controller => 'static_pages', :action => 'mainmenu', :as => 'main_menu'
  get "/mileagefilingdisplay"  => 'static_pages#mileagefilingdisplay'
  get "/disclaimer_filing"     => 'static_pages#disclaimer_filing'

  #PROFILES
  resource :profiles

  # TRIPS
  resources :trips

  get  "/trips/:id"           => "trips#show"
  post "/trips/:id"           => "trips#update"
  get  "/trips/:id/confirm"   => "trips#confirm"
  get  "/my_trips"            => "trips#my_trips"
  get  "/filing1"             => "trips#filing1"
  get  "/filing2"             => "trips#filing2"
  get  "/filing3"             => "trips#filing3"
  get "/mileagefilingdisplay" => 'trips#mileagefilingdisplay'


  #Vehicle
  resources :vehicles
  get   "/vehicles/:id/confirm"  => "vehicles#confirm"
  get   "/my_vehicles"           => "vehicles#my_vehicles"

  #Job
  resources :jobs
  get    "/jobs/:id/confirm"  => "jobs#confirm"
  get    "/my_jobs"           => "jobs#my_jobs"
  post 'twilio/voice' => 'twilio#voice'


  authenticated :user do
    root to: 'static_pages#mainmenu'
  end
  root to: 'static_pages#landing', as: :landing


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, except: :landing

  def mainmenu
    @vehicles = current_user.vehicles
    @jobs = current_user.jobs
    @trips = current_user.trips(:order => 'created_at DESC')
    @trips = current_user.trips.page(params[:page]).per(10)

  end

  def landing
  end

   def update
    #@users = current_user
    @user = User.find(params[:id])
   end
  end

  def mileagefilingdisplay
  end

  def disclaimor_filing
  end

  def profile
   @profile.user = current_user
  end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/disclaimer_filing.html.erb
<div id="wrapper">

    <header>
      <nav class="main-nav">
       <h1 class="screen-title col-md-6 col-md-offset-4">Legal Disclaimer</h1>
      </nav>
    </header>

    <main id="disFile">
     <div class="col-md-6 col-md-offset-3">
      <p>
       The user hereby acknowledges that Tax Trax is not a substitute for the professional advice of a certified pulbic accountant or a tax attorney.  Therefore, the user agrees that Tax Trax will not be held liable by the user for any errors resulting from the user's failure to obtain proper advice from a CPA or Tax Lawyer.</p>

       <p>By Clicking and and continuing on User agrees to release Tax Trax and all it's assocaites from damages, claims, and suits on behalf of information filled out by the user and legal departments. Tax Trax can no be held responseable for Errors on the User's part frauldlent or otherwise.
      </p>
     </div>
     <br>

     <div id="agree" class="col-md-6 col-md-offset-3">
      <form action="filings/new" method="get">
      <input type="checkbox" name="disclaimer"  value="agree" required>I have read and agree to the terms and conditions<br>
      <br>
      <input id="agreeButton" class="btn-primary" type="submit" value="I agree to terms and conditions" />
      </form>
     </div>
    </main>

  </div>

app/views/static_pages/help.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.erb</p>

app/views/static_pages/landing.html.erb
<div>
  <fieldset class="formAction col-md-1 col-md-offset-8">
        <%= link_to "Sign in", new_user_session_path, class: "btn btn-info btn-block" %>
      </fieldset>
</div>

<div class="spacer-md">
</div>

<div class="col-md-6 text-center col-md-offset-3">
 <h1>Ditch the paper logbook.</h1>
 <div class="spacer-mic">
</div>
 <h4>Tax Trax is the digital record keeper that keeps track of your work mileage and helps you calculate it to get the most money back in tax rebates.</h4>
</div>

<div class="spacer-sm">
</div>

<div class="col-md-6 text-center col-md-offset-3">
 <a class="btn btn-success " href="/users/sign_up">Sign Up Today</a>
</div>

<div class="spacer">
</div>

<div class="col-md-8 text-center col-md-offset-2 ">
 <h2>If you are using your personal car for work, Tax Trax can give you a tax rebate.</h2>
 <div class="spacer-sm">
</div>
 <div id="forDuo" class="text-center col-md-offset-1">
 <div class="col-md-6">
  <h3 class="">Delivery Drivers</h3>
   <p>If you are working for someone and using your personal car to drive, you are spending money for work. Tax laws recognize that, and are willing to give you money back if you track your expenses.</p>
 </div>
 <div class="col-md-6">
  <h3 class="">Independent Contractors</h3>
   <p>If you work for yourself and use your personal car to drive, you are paying into your work. Tax laws also recognize that, and will give you your personal money back if you keep good records.</p>
 </div>
 </div>
</div>

<div class="spacer">
</div>

<div class="col-md-6 text-center col-md-offset-3">
 <h2>What are you waiting for?</h2>
 <h3>Set yourself up to save today</h3>
 <div class="spacer-sm">
</div>
 <a class="btn btn-success" href="/users/sign_up">Sign Up</a>
</div>

app/views/static_pages/mainmenu.html.erb
<header class="col-md-8 col-md-offset-2">

 <main id="mainmain" class="col-md-8 col-md-offset-2">
<div class="text-center">
<% if current_user.trips.count > 0 %>
 <a id="NewTrip" class="btn btn-default btn-lg btn-success" href="/trips/new">&nbsp;&nbsp;&nbsp;Go for A Drive&nbsp;&nbsp;&nbsp;</a>
<% end %>
</div>

</header>
<div class="spacer-sm"></div>
<div id="statBar" class="col-md-8 col-md-offset-2 table-responsive  contextual-interest">
   <% @vehicles.each do |vehicle| %>
   <!--% @current_user.vehicles.last do %-->
    <table class="col-md-5 col-md-offset-2 col-xs-8 table">
     <tr class="col-md-8 col-md-offset-2"><h3 class="text-left col-md-offset-2">Driving Stats</h3></tr>
     <tr>
      <td class="stat"><%= vehicle.trips.count %> Trips</td>
      <td class="stat"><%= vehicle.total_miles_yearly(Time.current.year) %> Miles</td>
      <td class="stat">&nbsp;<span class="text-interest"><%= number_to_currency vehicle.running_rate(Time.current.year) %></span> savings</td>
     </tr>
    </table>
   <% end %>
</div>

 <% if current_user.vehicles.count < 1 and current_user.jobs.count < 1 %>
   <div class="col-md-6 col-md-offset-3 text-center">
    <div class="panel panel-default text-center ">
    <div class="panel-heading"><h3 class="panel-title"></h3></div>
   <div id="triggerModal" class="modalDialog">
    <div class="text-center">
     <h3 class="panel-title"><a href="#triggerModal" title="Close" class="close"></a></h3>
     <h2 class="screen-title text-center">Welcome to Tax Trax</h2>
     <h5 class="text-center">
       <p>To get started you need to</p>
       <a class="btn btn-success" href="/vehicles/new">Add A New Vehicle</a>
       and
       <a class="btn btn-success" href="/jobs/new">Add A New Job</a>
     </h5>
     <hr>
     <h4>Please remember that your commute to work does not count as a business trip.</h4>
    </div>
   </div>
    </div>
   </div>
  <% end %>

<% if current_user.jobs.count == 0 and current_user.vehicles.count >= 1  %>
 <div class="col-md-6 col-md-offset-3 text-center">
    <div class="panel panel-default text-center ">
    <div class="panel-heading"><h3 class="panel-title"></h3></div>
   <div id="triggerModal" class="modalDialog">
    <div class="text-center">
     <h3 class="panel-title"><a href="#triggerModal" title="Close" class="close"></a></h3>
     <h2 class="screen-title text-center">No job entered</h2>
     <h5 class="text-center">
       To continue your <strong>Tax Trax</strong> setup you still need to
       <div class="spacer-mic"></div>
       <a class="btn btn-success" href="/jobs/new">Add A Job</a>
     </h5>
     <hr>
     <h4>Please remember that your commute to work does not count as a business trip.</h4>
    </div>
   </div>
    </div>
   </div>
<% end %>


<% if current_user.vehicles.count == 0 and current_user.jobs.count >= 1   %>
 <div class="col-md-6 col-md-offset-3 text-center">
    <div class="panel panel-default text-center ">
    <div class="panel-heading"><h3 class="panel-title"></h3></div>
   <div id="triggerModal" class="modalDialog">
    <div class="text-center">
     <h3 class="panel-title"><a href="#triggerModal" title="Close" class="close"></a></h3>
     <h2 class="screen-title text-center">No vehicle entered</h2>
     <h5 class="text-center">
       To continue your <strong>Tax Trax</strong> setup you still need to
       <div class="spacer-mic"></div>
       <a class="btn btn-success" href="/vehicles/new">Add A Vehicle</a>
     </h5>
     <hr>
     <h4>Please remember that your commute to work does not count as a business trip.</h4>
    </div>
   </div>
    </div>
   </div>
<% end %>

<hr>
 <h3 class="screen-title col-md-6 col-md-offset-3 text-left">Driving Log</h3> <!-- col-md-offset-2 -->
 <div class="mainly text-center">
 <% if current_user.trips.count < 1 %>
  <div class="col-md-8 col-md-offset-2 text-center">
    <div class="panel panel-default text-center">
    <div class="panel-heading"><h3 class="panel-title"></h3></div>
   <div id="triggerModal" class="modalDialog">
    <div class="text-center">
     <h3 class="panel-title"><a href="#triggerModal" title="Close" class="close"></a></h3>
     <h2 class="screen-title text-center">No trips yet entered</h2>
     <h5 class="text-center">
     This is where your list of trips will show up once you have done the inital set up and make some trips.
     <%- if current_user.vehicles.count > 0 && current_user.jobs.count > 0 %>
       <div class="spacer-mic"></div>
       <a id="NewTrip" class="btn btn-default btn-lg btn-success" href="/trips/new">+ New Trip</a>
     <% end -%>
     </h5>
     <hr>
     <h4>Please remember that your commute to work does not count as a business trip.</h4>
    </div>
   </div>
    </div>
   </div>
   </div>
   <% end %>



  <div class="col-md-6 col-md-offset-3 text-center"><%= paginate @trips %></div>

  <% @trips.each do |trip| %>
   <dl>
   <div class="col-md-6 col-md-offset-3 isotope-item text-left">
   <div class="panel panel-default">
    <div class="spacer-sm"></div>
    <dd class="shower"><p><%= trip.vehicle.make_model %> driven for <%= trip.job.name %></p>
    </dd>
    <dd class="shower"><p><span class="text-interest"><%= number_to_currency trip.rebate %></span></strong> saved on <strong><%= trip.miles %></strong> miles</p>
    </dd>
    <br>

    <%= link_to 'Edit', "/trips/#{trip.id}/edit", :class => 'tipper1 btn btn-default btn-xs' %>
    <%= link_to 'Delete', "/trips/#{trip.id}", method: :delete, :class => 'tipper1 btn btn-default btn-xs' %>
    <div class="spacer-mic"></div>
    </div>
    <br>

    </dl>
  <% end %>
 </div>
 </div>
</main>

app/views/static_pages/mainmenu_backup.html.erb
<style>
 #statBar {
  border: 1px solid black;
  width: 100%;
  height: 50px;
  text-align: center;
 }

 #statBar tr {
  text-align: center;
 }

 .stat{
  color: green;
  padding: 10px;
 }

 .stat strong {
  color: black;
 }

</style>

<header>
    <nav class="main-nav">
      <h1 class="sign-in">Tax Trax</h1>
      <h1 class="screen-title">Main Menu</h1>
      <%= image_tag current_user.avatar.url(:medium), class: "img-rounded" %>
    </nav>
  </header>

  <div id="statBar">
   <% @vehicles.each do |vehicle| %>
    <table>
     <tr>
      <td class="stat"><%= vehicle.trips.count %>&nbsp;<strong>Trips</strong></td>
      <td class="stat"><%= vehicle.total_miless %>&nbsp;<strong>Miles</strong></td>
      <td class="stat"><strong>$</strong>&nbsp;<%= vehicle.rebaite_rate %><%= vehicle.rebaite_rate %></td>
     </tr>
    </table>
   <% end %>
  </div>

  <% if current_user.sign_in_count == 1 %>
  <div id="triggerModal" class="modalDialog">
   <div>
     <a href="#triggerModal" title="Close" class="close">X</a>
     <h2>Welcome to Tax Trax</h2>
     <ol>
       <li>Add a <%= link_to('vehicle', new_vehicle_path) %>  to your profile. You can add additional vehicles by selecting "Vehicle Info" on the main menu.</li>
       <li>Add your <%= link_to('job', new_job_path) %>  to your profile. You can add additional jobs by selecting "Job Info" on the main menu.</li>
     </ol>
   </div>
  </div>
  <% end %>

<main id="mainmain">

  <h2><%= current_user.first_name %></h2>

<div>
 <a id="NewTrip" class="btn" href="/trips/new">+ New Trip</a>
</div>


<ul id="mainmenuoptions">
  <li><a href="/my_trips" class="btn btn-sm">Driving Log</a></li>
  <li><a href="/disclaimer_filing" class="btn btn-sm">Tax Filing</a></li>
</ul>

<hr>
<h3 class="panel-title">Trips</h3>
</main>

app/views/static_pages/mileagefilingdisplay.html.erb
  <style>
  table, th, tr, td {
  outline: 1px solid black;
  }

  table {
   text-align: left;
  }
  </style>
<body>
  <div id="wrapper">

    <header>
      <nav class="main-nav">
        <ul>
          <li class="nav-left">
            <a href="/">Back</a>
          </li>
          <li class="nav-center">
            <h1 class="screen-title">
              Vehicle Expense
            </h1>
          </li>
        </ul>
      </nav>
    </header>

    <main>
     <table style="width:100%">
  <tr>
    <th>Section A-General Information (You must complete this section if you are calming vehicle expenses.)</th>
    <td></td>
    <th>(a) Vehicle</th>
    <th>(b) Vehicle</th>
  </tr>
  <tr>
    <td>11. Enter the date the vehicle was placed in service</td>
    <td>11</td>
    <td><%= @user.vehicle.created_at %></td>
    <td></td>
  </tr>
  <tr>
    <td>12. Total miles vehicle was driven during 2014</td>
    <td>12</td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>13. Business miles included on line 12</td>
    <td>13</td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>14. Percent of business use. Divide line 13 by line 12</td>
    <td>14</td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>15. Average daily roundtrip commuting distance</td>
    <td>15</td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>16. Commuting miles included on line 12</td>
    <td>16</td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>17. Other miles. Add lines 13 and 16 and subtract the total from line 12</td>
    <td>17</td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>18. Was your vehicle available for personal use during off-duty hours?</td>
    <td></td>
  </tr>
  <tr>
    <td>19. Do you or your spouce have another vehicle availble for personal use?</td>
    <td></td>
  </tr>
  <tr>
    <td>20. Do you have evidence to support your deduction?</td>
    <td></td>
  </tr>
  <tr>
    <td>21. If "Yes", is the evidence written?</td>
    <td></td>
  </tr>
  <tr>
  <th>Section B -Standard Mileage Rate</th>
  </tr>
  <tr>
  <td>22. Multiply line 13 by .56 cents(.56)</td>
  <td></td>
  </tr>
</table>

</body>
</html>
    </main>
  </div>
</body>