config/routes.rb
Rails.application.routes.draw do
  resources :year_ending_odometers

  resources :filings

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # Routes for Static Pages

  get "/mainmenu", :controller => 'static_pages', :action => 'mainmenu', :as => 'main_menu'
  get "/mileagefilingdisplay"  => 'static_pages#mileagefilingdisplay'
  get "/disclaimer_filing"     => 'static_pages#disclaimer_filing'

  #PROFILES
  resource :profiles

  # TRIPS
  resources :trips

  get  "/trips/:id"           => "trips#show"
  post "/trips/:id"           => "trips#update"
  get  "/trips/:id/confirm"   => "trips#confirm"
  get  "/my_trips"            => "trips#my_trips"
  get  "/filing1"             => "trips#filing1"
  get  "/filing2"             => "trips#filing2"
  get  "/filing3"             => "trips#filing3"
  get "/mileagefilingdisplay" => 'trips#mileagefilingdisplay'


  #Vehicle
  resources :vehicles
  get   "/vehicles/:id/confirm"  => "vehicles#confirm"
  get   "/my_vehicles"           => "vehicles#my_vehicles"

  #Job
  resources :jobs
  get    "/jobs/:id/confirm"  => "jobs#confirm"
  get    "/my_jobs"           => "jobs#my_jobs"
  post 'twilio/voice' => 'twilio#voice'


  authenticated :user do
    root to: 'static_pages#mainmenu'
  end
  root to: 'static_pages#landing', as: :landing


end

app/models/year_ending_odometer.rb
class YearEndingOdometer < ActiveRecord::Base
  belongs_to :vehicle
  belongs_to :filing
end

app/controllers/year_ending_odometers_controller.rb
class YearEndingOdometersController < ApplicationController
  before_action :set_year_ending_odometer, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @year_ending_odometers = YearEndingOdometer.all
    respond_with(@year_ending_odometers)
  end

  def show
    respond_with(@year_ending_odometer)
  end

  def new
    @year_ending_odometer = YearEndingOdometer.new
    respond_with(@year_ending_odometer)
  end

  def edit
  end

  def create
    @year_ending_odometer = YearEndingOdometer.new(year_ending_odometer_params)
    @year_ending_odometer.save
    redirect_to :back
  end

  def update
    @year_ending_odometer.update(year_ending_odometer_params)
    respond_with(@year_ending_odometer)
  end

  def destroy
    @year_ending_odometer.destroy
    respond_with(@year_ending_odometer)
  end

  private
    def set_year_ending_odometer
      @year_ending_odometer = YearEndingOdometer.find(params[:id])
    end

    def year_ending_odometer_params
      params.require(:year_ending_odometer).permit(:year, :reading, :vehicle_id)
    end
end

app/helpers/year_ending_odometers_helper.rb
module YearEndingOdometersHelper
end

app/views/year_ending_odometers/_form.html.erb
<%= form_for(@year_ending_odometer) do |f| %>
  <% if @year_ending_odometer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@year_ending_odometer.errors.count, "error") %> prohibited this year_ending_odometer from being saved:</h2>

      <ul>
      <% @year_ending_odometer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :reading %><br>
    <%= f.number_field :reading %>
  </div>
  <div class="field">
    <%= f.label :vehicle_id %><br>
    <%= f.collection_select :vehicle_id, current_user.vehicles, :id, :make_model %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/year_ending_odometers/edit.html.erb
<h1>Editing year_ending_odometer</h1>

<%= render 'form' %>

<%= link_to 'Show', @year_ending_odometer %> |
<%= link_to 'Back', year_ending_odometers_path %>

app/views/year_ending_odometers/index.html.erb
<h1>Listing year_ending_odometers</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>Reading</th>
      <th>Vehicle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @year_ending_odometers.each do |year_ending_odometer| %>
      <tr>
        <td><%= year_ending_odometer.year %></td>
        <td><%= year_ending_odometer.reading %></td>
        <td><%= year_ending_odometer.vehicle.make_model %></td>
        <td><%= link_to 'Show', year_ending_odometer %></td>
        <td><%= link_to 'Edit', edit_year_ending_odometer_path(year_ending_odometer) %></td>
        <td><%= link_to 'Destroy', year_ending_odometer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Year ending odometer', new_year_ending_odometer_path %>

app/views/year_ending_odometers/new.html.erb
<h1>New year_ending_odometer</h1>

<%= render 'form' %>

<%= link_to 'Back', year_ending_odometers_path %>

app/views/year_ending_odometers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @year_ending_odometer.year %>
</p>

<p>
  <strong>Reading:</strong>
  <%= @year_ending_odometer.reading %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @year_ending_odometer.vehicle %>
</p>

<%= link_to 'Edit', edit_year_ending_odometer_path(@year_ending_odometer) %> |
<%= link_to 'Back', year_ending_odometers_path %>