config/routes.rb
Rails.application.routes.draw do
  resources :year_ending_odometers

  resources :filings

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # Routes for Static Pages

  get "/mainmenu", :controller => 'static_pages', :action => 'mainmenu', :as => 'main_menu'
  get "/mileagefilingdisplay"  => 'static_pages#mileagefilingdisplay'
  get "/disclaimer_filing"     => 'static_pages#disclaimer_filing'

  #PROFILES
  resource :profiles

  # TRIPS
  resources :trips

  get  "/trips/:id"           => "trips#show"
  post "/trips/:id"           => "trips#update"
  get  "/trips/:id/confirm"   => "trips#confirm"
  get  "/my_trips"            => "trips#my_trips"
  get  "/filing1"             => "trips#filing1"
  get  "/filing2"             => "trips#filing2"
  get  "/filing3"             => "trips#filing3"
  get "/mileagefilingdisplay" => 'trips#mileagefilingdisplay'


  #Vehicle
  resources :vehicles
  get   "/vehicles/:id/confirm"  => "vehicles#confirm"
  get   "/my_vehicles"           => "vehicles#my_vehicles"

  #Job
  resources :jobs
  get    "/jobs/:id/confirm"  => "jobs#confirm"
  get    "/my_jobs"           => "jobs#my_jobs"
  post 'twilio/voice' => 'twilio#voice'


  authenticated :user do
    root to: 'static_pages#mainmenu'
  end
  root to: 'static_pages#landing', as: :landing


end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="pull-left" role="button"  >
    <!--%- if < (width: 300px) %-->
    <ul class="pull-right list-inline">
      <% if current_user %>
          <li class="">
            <button type="button" class="navbar-toggle dropdown-toggle" data-toggle="dropdown" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

            <ul id="nav-drop" style="float: right" class="dropdown-menu" role="menu">

              <li><%= link_to "Dashboard", main_menu_url %></li>

              <li><%= link_to "Vehicles", vehicles_url %></li>

              <li><%= link_to "Jobs", jobs_url %></li>

              <%- if controller_name != 'filings'  %>
              <%-if current_user.trips.count > 0 %>
              <li><%= link_to "Tax Filing", 'disclaimer_filing' %></li>
              <% end -%>
             <% end -%>

              <li class="divider"></li>
              <li><a><%= link_to "Sign Out", destroy_user_session_path, :method =>"delete" %></a></li>
            </ul>
          </li>
        <% end %>
    </ul>

    <!--% else %-->
      <!--%= link_to "TaxTrax", root_url, class: "navbar-brand col-md-1 col-md-offset-3" %-->
    <!--% end -%-->
    </div>

    <ul class="pull-right list-inline">
      <% if current_user %>
          <li><%= image_tag current_user.avatar.url(:thumb), class: "navbar-image" %></li>
          <li class="">
            <a class="btn btn-success" href="/profiles"><%=  current_user.first_name %></a>
          </li>
        <% end %>
    </ul>
  </div><!-- /.container-fluid -->
</nav>